# A simple instruction on why lapply will properly assign names
# to the list product known as "pre.shuffle". This list is generated by
# lapply(lst, function(x) do.call(set_aes, x)) and is essentially
# just the guts of aes() applied to every list element after all remappings

s <- structure(c("mpg", "mpg", "mpg",
                 "cyl", "cyl", "disp"),
               class = "uneval")
print(s)

# Only works on first "element" -------------------------------------------


# this will not work because s is of typeof() "character".
# only the first "uneval" object will have name "x"
s <- `names<-`(s, "y")
print(s)

# this will produce the same results
names(s) <- "x"
print(s)



# "Static" methods will only rename one and erase other renames -----------

# this will allow you to rename any "uneval" object
# but the first name will not appear when s is called
# only the most recent will be recorded
s <- `names<-`(s[1], "z")
s <- `names<-`(s[2], "z")
print(s)


# this does not work
names(s[[3]]) <- "x"
# but this does
names(s)[3] <- "x"



